name: PR to Develop

on:
  pull_request:
    branches:
      - develop   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # PASO a: BUILD - Ejemplo para Node.js
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build   

      # PASO b: TEST
      - name: Run tests
        run: npm test
